### ISSUE TITLE
Add the options for creating interactive transcripts and subtitles

### ISSUE THREAD

**Issue by neilstapleton** [bdecentgmbh/moodle-mod_videotime#11]
Hi Stefan

We're seeing an increasing need to ensure our videos are as accessible as possible. and we are using [3PlayMedia](https://www.3playmedia.com/) for our transcriptions. they offer [integration for Vimeo](https://www.3playmedia.com/solutions/features/integrations/vimeo-integration/) and [guidance for Moodle](https://www.3playmedia.com/solutions/how-it-works/how-to-guides/how-to-add-captions-and-subtitles-to-videos-in-moodle/).

It would be great to see some features in VideoTime to handle subtitles and interactive transcripts.  Is there anything in the pipeline?

I'm happy to provde more detail of what I'm looking for but the 3PlayMedia links above tell the story really.

Best
Neil

**Comment by stefanscholz** [comment]
Hi Neil,

first of all, appreciate your input!

Have you looked into chapters, subtitles and captions directly on Vimeo? Video Time is using Vimeo's own player, i.e. most features should work in Video Time as well. Having a quick look at the guidance site you linked to, I would assume that you can simply add those captions directly in the Vimeo video (which should then automatically be available in video time). Can you check if that would help?

We currently plan the next release of Video Time (as always...  after the release is before the release...) – and consider enhancing the player by adding additional elements to it, like "info on the author", "transcript", "related resources", "related videos" and "synced content" (the last one means that you can add content to parts of the video, e.g. from 0-30s show x, from 30-90s show y etc.)  – this is all in a very early stage though, nothing is decided yet. 

Best
Stefan

**Comment by stefanscholz** [comment]
Took us a lot longer, but interactive transcripts are now available in Video Time Business.

**Comment by jprovasnik** [comment]
Hi - is it possible outside of Vimeo? My work doesn't permit Vimeo since there's a disagreement in the Privacy Policy, so we load the video directly into the VideoTime Activity in the Moodle Course -- what might be the best suggestion for using   existing caption files with this method?
Thank you,
