### ISSUE TITLE
Security Issues found during a review with WhiteSource

### ISSUE THREAD

**Issue by johnpap21** [bdecentgmbh/moodle-mod_videotime#31]
Hi
During a review carried out on our site, we found there is an issue:
"that the plugin is still consuming a vulnerable version of symfony/http-foundation, which WhiteSource is picking up."

We have a subscribed version of the plugin as well.

Regards
JP

**Comment by stefanscholz** [comment]
Note: the issues found by the automated test were in the pro version, not the free version. They are fixed in the latest version of Video Time (1.5).
