### ISSUE TITLE
null is not a valid default for global settings

### ISSUE THREAD

**Issue by davosmith** [bdecentgmbh/moodle-mod_videotime#33]
Several of the global settings in settings.php have invalid null defaults - this results in Behat tests being broken across the entire site (because the first time an admin logs in, for a test with Javascript disabled, they get a page asking them to supply a value for those settings)

The settings affected at:
* videotime/height
* videotime/width
* videotime/maxheight
* videotime/maxwidth

**Comment by davosmith** [comment]
Also videotime/columns and videotime/preview_picture have defaults of 0, which doesn't match any of the available options for those settings, causing similar issues to the above.

**Comment by stefanscholz** [comment]
Hi @davosmith,

Thanks for reporting this issue!
Which version/branch are you reviewing?

Thanks
Stefan

**Comment by davosmith** [comment]
I can see the issue on the master branch: https://github.com/bdecentgmbh/moodle-mod_videotime/blob/master/settings.php#L99 (and the lines below).

The second set can be seen here: https://github.com/bdecentgmbh/moodle-mod_videotime/blob/master/settings.php#L269
(options are 1,2,3,4 - but the default is 0; options are PREVIEW_PICTURE_BIG, etc., but the default is 0)

**Comment by stefanscholz** [comment]
Hi Davo,

this should be fixed now on the master branch.

Best
Stefan

**Comment by davosmith** [comment]
Great - that looks much better.
