### ISSUE TITLE
Is youtube supported at all?

### ISSUE THREAD

**Issue by deligant** [bdecentgmbh/moodle-mod_videotime#46]
The plugin page on moodle website (https://moodle.org/plugins/mod_videotime) states that videotime can "Embed videos from Vimeo and Youtube easily in your course", but the documentation says that "While there are plans to support other sources (like YouTube), currently, only Vimeo is supported" (https://docs.moodle.org/402/en/VideoTime).
Vimeo has a cap of 2TB bandwidth per month and is VERY expensive when you go above that threshold so as we have a professional account on youtube we would prefer to have our videos hosted on youtube than paying huge amounts to Vimeo.
Thank you very much for shedding light on this issue.

**Comment by stefanscholz** [comment]
My bad @deligant , missed that reference in the documentation. YouTube is supported, yes! And also uploaded files direct in video time, as well as links to other hosting providers, e.g. using dash links or direct links to mp4 files. We'll update the documentation shortly.

Cheers
Stefan
