### ISSUE TITLE
Vimeo activity not support in Moodle mobile app

### ISSUE THREAD

**Issue by ErKaran98** [bdecentgmbh/moodle-mod_videotime#76]
I added Vimeo video through Vimeo activity form the moodle site. But when I open moodle mobile app then I show the error like "Uh ohh your organization added plugin not supported yet". My vimeo activity not work in Moodle app.

Please give me solution for it  it helps for me.

**Comment by stefanscholz** [comment]
Hi @ErKaran98, is it possible that you have only installed the free version? App support is only available in the pro version: https://bdecent.de/video-time/

Hope this helps!
Stefan
